# Generated by Django 2.0.1 on 2018-01-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_region_name_region_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_name',
            name='logo',
            field=models.ImageField(blank=True, upload_to='team_logos'),
        ),
    ]
